# Generated by Django 6.1 on 2026-08-22 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('REQUEST', 'Request'), ('CORRESPONDENCE', 'Correspondence'), ('PAYROLL', 'Payroll'), ('DOCUMENT', 'Document'), ('SYSTEM', 'System')], default='INFO', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
