# Generated by Django 6.1 on 2026-08-13 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0003_employeecontract_employeedocument_employeeevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ماه')),
                ('monthly_wage', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مزد ماهیانه')),
                ('worker_food_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بن کارگری')),
                ('housing_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق مسکن')),
                ('child_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق اولاد')),
                ('marriage_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق تأهل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'حقوق و مزایا',
                'verbose_name_plural': 'حقوق و مزایا',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_employee_salary_period')],
            },
        ),
    ]
