# Generated by Django 6.1 on 2026-08-14 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='child_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حق مسکن'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='marriage_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حق تأهل'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='monthly_wage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مزد ماهیانه'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='worker_food_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بن کارگری'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1300)], verbose_name='سال'),
        ),
    ]
