# Generated by Django 6.1 on 2026-08-14 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employeesalary_child_allowance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('insurance', 'بیمه'), ('tax', 'مالیات'), ('advance', 'مساعده'), ('loan', 'وام'), ('absence', 'غیبت / کسرکار'), ('other', 'سایر')], max_length=30, verbose_name='نوع کسور')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.employeesalary', verbose_name='حقوق')),
            ],
            options={
                'verbose_name': 'کسور حقوق',
                'verbose_name_plural': 'کسورات حقوق',
                'ordering': ['deduction_type', 'id'],
            },
        ),
    ]
