# Generated by Django 6.1 on 2026-08-31 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrolldeduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پاداش')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='payroll.employeesalary', verbose_name='حقوق')),
            ],
            options={
                'verbose_name': 'پاداش حقوق',
                'verbose_name_plural': 'پاداش\u200cهای حقوق',
                'ordering': ['id'],
            },
        ),
    ]
