# Generated by Django 6.1 on 2026-08-13 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=50, unique=True, verbose_name='کد پرسنلی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('employee_group', models.CharField(choices=[('administrative', 'اداری'), ('production', 'تولید')], max_length=20, verbose_name='گروه')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='بخش / دپارتمان')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان شغلی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع به کار')),
                ('insurance_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بیمه شدن')),
                ('insurance_number', models.CharField(blank=True, max_length=50, verbose_name='شماره بیمه')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, verbose_name='شماره شناسنامه')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='آخرین مدرک تحصیلی')),
                ('field_of_study', models.CharField(blank=True, max_length=150, verbose_name='رشته تحصیلی')),
                ('student_number', models.CharField(blank=True, max_length=100, verbose_name='شماره دانشجویی')),
                ('military_status', models.CharField(blank=True, choices=[('subject', 'مشمول'), ('exemption', 'معافیت'), ('completed', 'پایان خدمت'), ('serving', 'در حال خدمت'), ('educational_exemption', 'معافیت تحصیلی')], max_length=30, verbose_name='وضعیت نظام وظیفه')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل'), ('separated', 'متارکه'), ('widowed', 'بیوه')], max_length=20, verbose_name='وضعیت تأهل')),
                ('child_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد فرزند')),
                ('landline_phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن ثابت')),
                ('residence_area', models.CharField(blank=True, max_length=100, verbose_name='منطقه سکونت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('transportation_status', models.CharField(blank=True, choices=[('personal', 'شخصی'), ('service', 'سرویس')], max_length=20, verbose_name='وضعیت تردد')),
                ('transportation_description', models.TextField(blank=True, verbose_name='توضیحات سرویس')),
                ('contract_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان قرارداد')),
                ('contract_position', models.CharField(blank=True, max_length=150, verbose_name='سمت درج شده در قرارداد')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='پرسنل فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
