# Generated by Django 6.1 on 2026-08-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=30, verbose_name='شماره کارت')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='شماره شبا')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('is_primary', models.BooleanField(default=False, verbose_name='حساب اصلی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='EmployeeChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرزند')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('education_certificate', models.BooleanField(default=False, verbose_name='گواهی اشتغال به تحصیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'فرزند',
                'verbose_name_plural': 'فرزندان',
                'ordering': ['birth_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('mobile', 'موبایل')], default='mobile', max_length=20, verbose_name='نوع تلفن')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('is_primary', models.BooleanField(default=False, verbose_name='شماره اصلی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'تلفن پرسنل',
                'verbose_name_plural': 'تلفن\u200cهای پرسنل',
            },
        ),
        migrations.CreateModel(
            name='EmployeePromissoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(max_length=100, verbose_name='شماره سفته')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promissory_notes', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'سفته',
                'verbose_name_plural': 'سفته\u200cها',
            },
        ),
    ]
