# Generated by Django 6.1 on 2026-08-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_employeebankaccount_employeechild_employeephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('temporary', 'موقت'), ('project', 'پروژه\u200cای'), ('other', 'سایر')], max_length=30, verbose_name='نوع قرارداد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قرارداد')),
                ('position', models.CharField(max_length=200, verbose_name='سمت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع قرارداد')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان قرارداد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='personnel/contracts/%Y/%m/', verbose_name='فایل قرارداد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قرارداد فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'قرارداد پرسنل',
                'verbose_name_plural': 'قراردادهای پرسنل',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'کارت ملی'), ('birth_certificate', 'شناسنامه'), ('military_card', 'کارت پایان خدمت / معافیت'), ('education', 'مدرک تحصیلی'), ('insurance', 'مدرک بیمه'), ('no_criminal_record', 'عدم سوءپیشینه'), ('no_addiction', 'عدم اعتیاد'), ('occupational_health', 'طب کار'), ('contract', 'قرارداد'), ('other', 'سایر')], max_length=50, verbose_name='نوع مدرک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک')),
                ('file', models.FileField(upload_to='personnel/documents/%Y/%m/', verbose_name='فایل مدرک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'مدرک پرسنلی',
                'verbose_name_plural': 'مدارک پرسنلی',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نمره ارزیابی')),
                ('evaluation_date', models.DateField(verbose_name='تاریخ ارزیابی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='personnel.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'ارزیابی پرسنل',
                'verbose_name_plural': 'ارزیابی\u200cهای پرسنل',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
