# Generated by Django 6.1 on 2026-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_employeecontract_employeedocument_employeeevaluation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeepromissorynote',
            constraint=models.UniqueConstraint(fields=('employee', 'note_number'), name='unique_promissory_note_per_employee'),
        ),
    ]
