# Generated by Django 6.1 on 2026-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_employeepromissorynote_unique_promissory_note_per_employee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='unique_primary_bank_account_per_employee'),
        ),
    ]
