# Generated by Django 6.1 on 2026-08-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('personnel', '0005_employeebankaccount_unique_primary_bank_account_per_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.position', verbose_name='پست سازمانی'),
        ),
    ]
