# Generated by Django 6.1 on 2026-08-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد واحد')),
                ('name', models.CharField(max_length=150, verbose_name='نام واحد')),
                ('unit_type', models.CharField(choices=[('company', 'شرکت'), ('management', 'مدیریت'), ('deputy', 'معاونت'), ('department', 'دپارتمان'), ('unit', 'واحد'), ('section', 'بخش')], max_length=20, verbose_name='نوع واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.organizationunit', verbose_name='واحد والد')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'verbose_name_plural': 'واحدهای سازمانی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد پست')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.organizationunit', verbose_name='واحد سازمانی')),
            ],
            options={
                'verbose_name': 'پست سازمانی',
                'verbose_name_plural': 'پست\u200cهای سازمانی',
                'ordering': ['title'],
            },
        ),
    ]
