# Generated by Django 6.1 on 2026-08-20 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('personnel', 'مدرک پرسنلی'), ('organization', 'مدرک سازمانی'), ('contract', 'قرارداد'), ('correspondence', 'مکاتبات'), ('financial', 'مالی'), ('administrative', 'اداری'), ('other', 'سایر')], max_length=30, verbose_name='نوع سند')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان سند')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='فایل سند')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری کننده')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
