# Generated by Django 6.1 on 2026-08-22 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('personnel', '0007_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_type', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('INTERNAL', 'Internal')], max_length=20)),
                ('letter_number', models.CharField(max_length=100)),
                ('letter_date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTERED', 'Registered'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_correspondences', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondences', to='personnel.employee')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondences', to='organization.organizationunit')),
            ],
            options={
                'ordering': ['-letter_date', '-id'],
                'indexes': [models.Index(fields=['letter_number'], name='corresponde_letter__dd541e_idx'), models.Index(fields=['correspondence_type', 'status'], name='corresponde_corresp_c11145_idx'), models.Index(fields=['employee', '-letter_date'], name='corresponde_employe_657c48_idx'), models.Index(fields=['organization_unit', '-letter_date'], name='corresponde_organiz_7f608a_idx'), models.Index(fields=['created_by', '-created_at'], name='corresponde_created_ad29bc_idx')],
            },
        ),
    ]
